apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prefect-ui.fullname" . }}-apollo
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: apollo
    {{- include "prefect-ui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ include "prefect-ui.fullname" . }}-apollo
  {{- toYaml .Values.prefect.apollo.replicas | nindent 2 }}