{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-ui.fullname" . }}
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: ingress
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  tls.crt: {{ default "" .Values.ingress.secrets.cert | b64enc | quote }}
  tls.key: {{ default "" .Values.ingress.secrets.key | b64enc | quote }}
type: kubernetes.io/tls
{{- end }}