apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prefect-ui.fullname" . }}-hasura
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: hasura
    {{- include "prefect-ui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ include "prefect-ui.fullname" . }}-hasura
  {{- toYaml .Values.prefect.hasura.replicas | nindent 2 }}