{{ if eq .Values.prefect.hasura.create true }}
# ref: https://github.com/hasura/graphql-engine/tree/master/install-manifests/kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-ui.fullname" . }}-hasura
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: hasura
    {{- include "prefect-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prefect.hasura.replicas.minReplicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: hasura
      {{- include "prefect-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hasura
        {{- include "prefect-ui.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      serviceAccountName: {{ include "prefect-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-postgres
          image: {{ .Values.prefect.busybox.image.repository }}
          command:
          - sh
          - '-c'
          - 'until nslookup {{ include "prefect-ui.name" . }}-postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "prefect-ui.name" . }}-postgres; sleep 2; done'
      containers:
        - name: hasura
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.prefect.hasura.image.repository }}"
          imagePullPolicy: {{ .Values.prefect.hasura.image.pullPolicy }}
          command:
          - graphql-engine
          - serve
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom: { secretKeyRef: { name: {{ include "prefect-ui.name" . }}-postgres, key: DATABASE_URL } }
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_SERVER_PORT
              value: "{{ .Values.prefect.hasura.service.port }}"
            - name: HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE
              value: "100"
            {{- with .Values.prefect.hasura.environment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.prefect.hasura.service.name }}
              containerPort: {{ .Values.prefect.hasura.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.prefect.hasura.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.prefect.hasura.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.prefect.hasura.resources | nindent 12 }}
      volumes: []
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{ end }}