{{ if .Values.prefect.hasura.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-ui.fullname" . }}-hasura
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: hasura
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  ADMIN_SECRET: {{ default "" .Values.prefect.hasura.secrets.adminSecret | b64enc | quote }}
{{ end }}