{{ if eq .Values.prefect.minio.create true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefect-ui.name" . }}-minio
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: minio
    {{- include "prefect-ui.labels" . | nindent 4 }}
#    app.kubernetes.io/component: minio
#    app.kubernetes.io/name: {{ include "prefect-ui.name" . }}
#    app.kubernetes.io/part-of: {{ default (include "prefect-ui.name" .) }}
#    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "files/configmap/minio*").AsConfig | nindent 2 }}
{{ end }}