{{ if eq .Values.prefect.minio.create true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-ui.name" . }}-minio
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: minio
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  MINIO_ACCESS_KEY: {{ default "" .Values.prefect.minio.secrets.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ default "" .Values.prefect.minio.secrets.secretKey | b64enc | quote }}
{{ end }}