{{ if .Values.minio }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-ui.name" . }}-minio
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: minio
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  MINIO_ACCESS_KEY: {{ default "" .Values.minio.accessKey.password | b64enc | quote }}
  MINIO_SECRET_KEY: {{ default "" .Values.minio.secretKey.password | b64enc | quote }}
{{ end }}