apiVersion: v2
icon: https://d33wubrfki0l68.cloudfront.net/452d2a3c0b72872c8a55dcc952543252684f2d33/567cd/assets/img/prefect-logo-full-flat-white.196a5c8b.svg
name: prefect-ui
description: A Helm chart to run Prefect UI on Kubernetes
keywords:
  - python
  - prefect
  - prefect-ui
home: https://github.com/szelenka/prefect-ui
sources:
  - https://github.com/szelenka/prefect-ui
maintainers:
  - name: Scott Zelenka
    email: https://github.com/szelenka
dependencies:
  - name: postgresql-ha
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: prefect.postgres.create
  - name: minio
    version: 3.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: prefect.minio.enabled
type: application
version: 0.1.0
# this is the Docker tag of prefect-server (once they start adding them)
appVersion: latest
