{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prefect-ui.fullname" . }}-agent
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
{{ include "prefect-ui.labels" . | nindent 4 }}
{{- end -}}
