{{ if eq .Values.prefect.postgres.create true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefect-ui.name" . }}-postgres
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "prefect-ui.labels" . | nindent 4 }}
#    app.kubernetes.io/component: postgres
#    app.kubernetes.io/name: {{ include "prefect-ui.name" . }}
#    app.kubernetes.io/part-of: {{ default (include "prefect-ui.name" .) }}
#    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "files/configmap/postgres*").AsConfig | nindent 2 }}
{{ end }}