apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefect-ui.name" . }}-postgres
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/configmap/postgres*").AsConfig | nindent 2 }}