{{ if .Values.prefect.postgres.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-ui.name" . }}-postgres
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ default "" .Values.prefect.postgres.secrets.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ default "" .Values.prefect.postgres.secrets.password | b64enc | quote }}
  POSTGRES_DB: {{ default "" .Values.prefect.postgres.secrets.database | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:%s/%s" .Values.prefect.postgres.secrets.username .Values.prefect.postgres.secrets.password (include "prefect-ui.name" .) (.Values.prefect.postgres.service.port | toString ) .Values.prefect.postgres.secrets.database| b64enc | quote }}
{{ end }}