{{ if index .Values "postgresql-ha" }}
{{ $username := index .Values "postgresql-ha" "postgresql" "username" }}
{{ $password := index .Values "postgresql-ha" "postgresql" "password" }}
{{ $port := (index .Values "postgresql-ha" "service" "port" | toString )}}
{{ $database := index .Values "postgresql-ha" "postgresql" "database" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-ui.name" . }}-postgres
  namespace: {{ include "prefect-ui.namespace" . }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "prefect-ui.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql-ha-pgpool:%s/%s" $username $password .Release.Name $port $database | b64enc | quote }}
  {{ end }}